name: CI World News
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  quality-check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: arno123
          POSTGRES_DB: wn_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install all dependencies
        run: |
          npm install
          npm install --prefix wn-falcon-reader/server
          npm install --prefix wn-falcon-reader/client
          npm install --prefix wn-falcon-writer/server
          npm install --prefix wn-falcon-writer/client

      - name: Initialize Databse Schema
        run: docker exec -i $(docker ps -qf name=postgres) psql -U postgres -d wn_db < ./init-db/init_db.sql

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Linter
        run: npm run lint:all

      - name: Run unit & integration tests (Vitest)
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: arno123
          DB_NAME: wn_db
          READER_BACK_PORT: 3001
          WRITER_BACK_PORT: 3002
        run: npm run test:all

      - name: Run E2E tests (Playwright)
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: arno123
          DB_NAME: wn_db
          READER_BACK_PORT: 3001
          WRITER_BACK_PORT: 3002
          READER_FRONT_PORT: 8081
          WRITER_FRONT_PORT: 8080
        run: npx playwright test
